// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.5.1
// source: researchClient.proto

package raft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqType *int64   `protobuf:"varint,1,req,name=reqType" json:"reqType,omitempty"` // 1: add, 2: delete, 3: search
	Args    []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
}

func (x *ResearchRequest) Reset() {
	*x = ResearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_researchClient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchRequest) ProtoMessage() {}

func (x *ResearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_researchClient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchRequest.ProtoReflect.Descriptor instead.
func (*ResearchRequest) Descriptor() ([]byte, []int) {
	return file_researchClient_proto_rawDescGZIP(), []int{0}
}

func (x *ResearchRequest) GetReqType() int64 {
	if x != nil && x.ReqType != nil {
		return *x.ReqType
	}
	return 0
}

func (x *ResearchRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ResearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"` // 序列化后的结果
	Success  *bool    `protobuf:"varint,2,req,name=success" json:"success,omitempty"`
	Redirect *string  `protobuf:"bytes,3,opt,name=redirect" json:"redirect,omitempty"`
	ErrorMsg *string  `protobuf:"bytes,4,opt,name=errorMsg" json:"errorMsg,omitempty"`
}

func (x *ResearchResponse) Reset() {
	*x = ResearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_researchClient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchResponse) ProtoMessage() {}

func (x *ResearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_researchClient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchResponse.ProtoReflect.Descriptor instead.
func (*ResearchResponse) Descriptor() ([]byte, []int) {
	return file_researchClient_proto_rawDescGZIP(), []int{1}
}

func (x *ResearchResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ResearchResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ResearchResponse) GetRedirect() string {
	if x != nil && x.Redirect != nil {
		return *x.Redirect
	}
	return ""
}

func (x *ResearchResponse) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

var File_researchClient_proto protoreflect.FileDescriptor

var file_researchClient_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x61, 0x66, 0x74, 0x22, 0x3f, 0x0a, 0x0f,
	0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x7c, 0x0a,
	0x10, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x32, 0x52, 0x0a, 0x15, 0x52,
	0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x15, 0x2e, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x52,
	0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x15, 0x5a, 0x13, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2f, 0x72, 0x61, 0x66, 0x74,
}

var (
	file_researchClient_proto_rawDescOnce sync.Once
	file_researchClient_proto_rawDescData = file_researchClient_proto_rawDesc
)

func file_researchClient_proto_rawDescGZIP() []byte {
	file_researchClient_proto_rawDescOnce.Do(func() {
		file_researchClient_proto_rawDescData = protoimpl.X.CompressGZIP(file_researchClient_proto_rawDescData)
	})
	return file_researchClient_proto_rawDescData
}

var file_researchClient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_researchClient_proto_goTypes = []interface{}{
	(*ResearchRequest)(nil),  // 0: raft.ResearchRequest
	(*ResearchResponse)(nil), // 1: raft.ResearchResponse
}
var file_researchClient_proto_depIdxs = []int32{
	0, // 0: raft.ResearchClientService.research:input_type -> raft.ResearchRequest
	1, // 1: raft.ResearchClientService.research:output_type -> raft.ResearchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_researchClient_proto_init() }
func file_researchClient_proto_init() {
	if File_researchClient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_researchClient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_researchClient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_researchClient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_researchClient_proto_goTypes,
		DependencyIndexes: file_researchClient_proto_depIdxs,
		MessageInfos:      file_researchClient_proto_msgTypes,
	}.Build()
	File_researchClient_proto = out.File
	file_researchClient_proto_rawDesc = nil
	file_researchClient_proto_goTypes = nil
	file_researchClient_proto_depIdxs = nil
}
